// Generated from mise.sdl.toml, scripts/sdl-release.ts, and scripts/codegen/config.ts by scripts/sync-package-metadata.ts. Do not edit.
const std = @import("std");

pub const translation_defines: []const []const u8 = &.{"SDL_DISABLE_OLD_NAMES=1"};

pub const prebuilt_linkage: []const u8 = "shared";

pub const PrebuiltTarget = struct {
    os: []const u8,
    abi: []const u8,
    arch: []const u8,
    family: []const u8,
    package_family: []const u8,
    upstream_arch: []const u8,
};

pub const prebuilt_targets = [_]PrebuiltTarget{
    .{ .os = "windows", .abi = "gnu", .arch = "x86", .family = "mingw", .package_family = "windows-gnu", .upstream_arch = "i686-w64-mingw32" },
    .{ .os = "windows", .abi = "gnu", .arch = "x86_64", .family = "mingw", .package_family = "windows-gnu", .upstream_arch = "x86_64-w64-mingw32" },
    .{ .os = "windows", .abi = "msvc", .arch = "x86", .family = "msvc", .package_family = "windows-msvc", .upstream_arch = "x86" },
    .{ .os = "windows", .abi = "msvc", .arch = "x86_64", .family = "msvc", .package_family = "windows-msvc", .upstream_arch = "x64" },
    .{ .os = "windows", .abi = "msvc", .arch = "aarch64", .family = "msvc", .package_family = "windows-msvc", .upstream_arch = "arm64" },
    .{ .os = "macos", .abi = "", .arch = "x86_64", .family = "macos", .package_family = "macos", .upstream_arch = "" },
    .{ .os = "macos", .abi = "", .arch = "aarch64", .family = "macos", .package_family = "macos", .upstream_arch = "" },
};

pub const WindowsOptionalRuntime = struct {
    mingw_architectures: []const []const u8,
    msvc_architectures: []const []const u8,
    dlls: []const []const u8,
    licenses: []const []const u8,
};

pub const PrebuiltKind = enum { shared, static };

pub const Library = struct {
    key: []const u8,
    id: []const u8,
    module_name: []const u8,
    abi_import_name: []const u8,
    source: []const u8,
    translation_unit: []const u8,
    include_directories: []const []const u8,
    dependencies: []const []const u8,
    library_name: []const u8,
    framework_name: []const u8,
    pkg_config_name: []const u8,
    minimum_version: []const u8,
    prebuilt: bool,
    prebuilt_kind: PrebuiltKind,
    source_build_directory: []const u8,
    macos_optional_frameworks: []const []const u8,
    windows_optional_runtime: ?WindowsOptionalRuntime,
};

pub const libraries = [_]Library{
    .{
        .key = "sdl",
        .id = "SDL3",
        .module_name = "sdl",
        .abi_import_name = "sdl3_c",
        .source = "src/sdl.zig",
        .translation_unit = "#include <SDL3/SDL.h>\n#include <SDL3/SDL_main.h>\n#include <SDL3/SDL_vulkan.h>\n#include <SDL3/SDL_revision.h>\n",
        .include_directories = &.{"vendor/SDL3/include"},
        .dependencies = &.{},
        .library_name = "SDL3",
        .framework_name = "SDL3",
        .pkg_config_name = "sdl3",
        .minimum_version = "3.4.12",
        .prebuilt = true,
        .prebuilt_kind = .shared,
        .source_build_directory = "",
        .macos_optional_frameworks = &.{},
        .windows_optional_runtime = null,
    },
    .{
        .key = "test",
        .id = "SDL3_test",
        .module_name = "test",
        .abi_import_name = "sdl3_test_c",
        .source = "src/test.zig",
        .translation_unit = "#include <SDL3/SDL_test.h>\n",
        .include_directories = &.{"vendor/SDL3/include"},
        .dependencies = &.{"sdl"},
        .library_name = "SDL3_test",
        .framework_name = "SDL3_test",
        .pkg_config_name = "SDL3_test",
        .minimum_version = "3.4.12",
        .prebuilt = true,
        .prebuilt_kind = .static,
        .source_build_directory = "",
        .macos_optional_frameworks = &.{},
        .windows_optional_runtime = null,
    },
    .{
        .key = "controller_image",
        .id = "ControllerImage",
        .module_name = "controller_image",
        .abi_import_name = "sdl3_controller_image_c",
        .source = "src/controller_image.zig",
        .translation_unit = "#include <controllerimage.h>\n",
        .include_directories = &.{ "vendor/ControllerImage/src", "vendor/SDL3/include" },
        .dependencies = &.{"sdl"},
        .library_name = "controllerimage",
        .framework_name = "ControllerImage",
        .pkg_config_name = "ControllerImage",
        .minimum_version = "0.0.2",
        .prebuilt = true,
        .prebuilt_kind = .static,
        .source_build_directory = "ControllerImage",
        .macos_optional_frameworks = &.{},
        .windows_optional_runtime = null,
    },
    .{
        .key = "shadercross",
        .id = "SDL3_shadercross",
        .module_name = "shadercross",
        .abi_import_name = "sdl3_shadercross_c",
        .source = "src/shadercross.zig",
        .translation_unit = "#include <SDL3_shadercross/SDL_shadercross.h>\n",
        .include_directories = &.{ "vendor/SDL3_shadercross/include", "vendor/SDL3/include" },
        .dependencies = &.{"sdl"},
        .library_name = "SDL3_shadercross",
        .framework_name = "SDL3_shadercross",
        .pkg_config_name = "SDL3_shadercross",
        .minimum_version = "3.0.0",
        .prebuilt = true,
        .prebuilt_kind = .shared,
        .source_build_directory = "",
        .macos_optional_frameworks = &.{},
        .windows_optional_runtime = null,
    },
    .{
        .key = "image",
        .id = "SDL3_image",
        .module_name = "image",
        .abi_import_name = "sdl3_image_c",
        .source = "src/image.zig",
        .translation_unit = "#include <SDL3_image/SDL_image.h>\n",
        .include_directories = &.{ "vendor/SDL3_image/include", "vendor/SDL3/include" },
        .dependencies = &.{"sdl"},
        .library_name = "SDL3_image",
        .framework_name = "SDL3_image",
        .pkg_config_name = "SDL3_image",
        .minimum_version = "3.4.4",
        .prebuilt = true,
        .prebuilt_kind = .shared,
        .source_build_directory = "",
        .macos_optional_frameworks = &.{ "avif", "jxl", "png", "webp" },
        .windows_optional_runtime = .{ .mingw_architectures = &.{ "x86", "x86_64" }, .msvc_architectures = &.{ "x86", "x86_64" }, .dlls = &.{ "libavif-16.dll", "libpng16-16.dll", "libtiff-6.dll", "libwebp-7.dll", "libwebpdemux-2.dll", "libwebpmux-3.dll" }, .licenses = &.{ "LICENSE.aom.txt", "LICENSE.avif.txt", "LICENSE.dav1d.txt", "LICENSE.libpng.txt", "LICENSE.tiff.txt", "LICENSE.webp.txt" } },
    },
    .{
        .key = "ttf",
        .id = "SDL3_ttf",
        .module_name = "ttf",
        .abi_import_name = "sdl3_ttf_c",
        .source = "src/ttf.zig",
        .translation_unit = "#include <SDL3_ttf/SDL_ttf.h>\n#include <SDL3_ttf/SDL_textengine.h>\n",
        .include_directories = &.{ "vendor/SDL3_ttf/include", "vendor/SDL3/include" },
        .dependencies = &.{"sdl"},
        .library_name = "SDL3_ttf",
        .framework_name = "SDL3_ttf",
        .pkg_config_name = "SDL3_ttf",
        .minimum_version = "3.2.2",
        .prebuilt = true,
        .prebuilt_kind = .shared,
        .source_build_directory = "",
        .macos_optional_frameworks = &.{},
        .windows_optional_runtime = null,
    },
    .{
        .key = "mixer",
        .id = "SDL3_mixer",
        .module_name = "mixer",
        .abi_import_name = "sdl3_mixer_c",
        .source = "src/mixer.zig",
        .translation_unit = "#include <SDL3_mixer/SDL_mixer.h>\n",
        .include_directories = &.{ "vendor/SDL3_mixer/include", "vendor/SDL3/include" },
        .dependencies = &.{"sdl"},
        .library_name = "SDL3_mixer",
        .framework_name = "SDL3_mixer",
        .pkg_config_name = "SDL3_mixer",
        .minimum_version = "3.2.4",
        .prebuilt = true,
        .prebuilt_kind = .shared,
        .source_build_directory = "",
        .macos_optional_frameworks = &.{ "gme", "ogg", "opus", "wavpack", "xmp" },
        .windows_optional_runtime = .{ .mingw_architectures = &.{ "x86", "x86_64" }, .msvc_architectures = &.{ "x86", "x86_64" }, .dlls = &.{ "libgme.dll", "libogg-0.dll", "libopus-0.dll", "libopusfile-0.dll", "libwavpack-1.dll", "libxmp.dll" }, .licenses = &.{ "LICENSE.gme.txt", "LICENSE.ogg-vorbis.txt", "LICENSE.opus.txt", "LICENSE.opusfile.txt", "LICENSE.wavpack.txt", "LICENSE.xmp.txt" } },
    },
    .{
        .key = "net",
        .id = "SDL3_net",
        .module_name = "net",
        .abi_import_name = "sdl3_net_c",
        .source = "src/net.zig",
        .translation_unit = "#include <SDL3_net/SDL_net.h>\n",
        .include_directories = &.{ "vendor/SDL3_net/include", "vendor/SDL3/include" },
        .dependencies = &.{"sdl"},
        .library_name = "SDL3_net",
        .framework_name = "SDL3_net",
        .pkg_config_name = "SDL3_net",
        .minimum_version = "3.2.0",
        .prebuilt = true,
        .prebuilt_kind = .shared,
        .source_build_directory = "",
        .macos_optional_frameworks = &.{},
        .windows_optional_runtime = null,
    },
};

pub fn byKey(key: []const u8) *const Library {
    inline for (&libraries) |*library| {
        if (std.mem.eql(u8, key, library.key)) return library;
    }
    @panic("unknown SDL library key");
}
