import { assert, assertEquals } from "@std/assert";

const aliases = [
  "errors",
  "value",
  "ownership",
  "geometry",
  "pixels",
  "blend",
  "keycode",
  "scancode",
  "guid",
  "version",
  "time",
  "power",
  "pen",
  "touch",
  "joystick",
  "mouse",
  "keyboard",
  "gamepad",
  "sensor",
  "net",
  "gpu",
  "message_box",
  "ttf",
  "mixer",
  "haptic",
  "video",
  "dialog",
  "process",
  "render",
  "surface",
  "surface_image",
  "audio",
  "camera",
  "io_stream",
  "async_io",
  "filesystem",
  "properties",
  "storage",
  "timer",
  "tray",
  "thread",
  "mutex",
  "image",
  "metal",
  "vulkan",
  "assert",
  "clipboard",
  "events",
  "hints",
  "log",
  "system",
  "app",
  "shader_assets",
  "extras",
];

Deno.test("public facade aliases compile through the package root", async () => {
  const root = await Deno.readTextFile("src/root.zig");
  for (const alias of aliases) assert(root.includes(`pub const ${alias}`), alias);
  const result = await new Deno.Command("zig", {
    args: ["build"],
    stdout: "piped",
    stderr: "piped",
  }).output();
  assertEquals(result.code, 0, new TextDecoder().decode(result.stderr));
});
